[package]
name = "pseudoterminal"
description = "A cross-platform pseudoterminal implementation with async support"
version = "0.1.0"
license = "MIT"
edition = "2021"

keywords = ["pty", "conpty", "terminal", "process"]
categories = ["asynchronous", "command-line-interface"]

[dependencies]
cfg-if = "1.0.0"
tokio = { version = "1.32.0", default-features = false, features = [
  "process",
  "fs",
], optional = true }

[target.'cfg(not(windows))'.dependencies]
nix = { version = "0.27.1", features = ["term", "ioctl", "process", "fs"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.0", features = [] }

[features]
non-blocking = ["dep:tokio"]
